### ISSUE TITLE
There is a big blank area in the bottom of the home page after I install this module.

### ISSUE THREAD

**Issue by eversatis** [OdooCommunityWidgets/website_product_attachments#1]
There is a big blank area on the bottom of the home page after I install this module. And there seems no way to change the tab name. Thank you!

**Comment by lukebranch** [comment]
@frankmiao2015 ,

This module is not yet ready to be installed. I'll post an update to this issue once the basic framework has been put in place.

**Comment by eversatis** [comment]
opps.. Sorry, I was supposed to open the issue in another addon developed by blooparks. Wrong place after open too many pages. I am closing it right now. And if you have intrerest, here is the link: https://github.com/blooparksystems/bp_snippet_tab_navigation

Best regards
